-- Full Hymns Data (398 hymns)
-- Generated from both LDS hymnals
-- Date: 2026-01-18

INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0001', 'Hymn #1 - The Morning Breaks', true, 1, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0002', 'Hymn #2 - The Spirit of God', true, 2, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0003', 'Hymn #3 - Now Let Us Rejoice', true, 3, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0004', 'Hymn #4 - Truth Eternal', true, 4, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0005', 'Hymn #5 - High on the Mountain Top', true, 5, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0006', 'Hymn #6 - Redeemer of Israel', true, 6, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0007', 'Hymn #7 - Israel, Israel, God Is Calling', true, 7, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0008', 'Hymn #8 - Awake and Arise', true, 8, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0009', 'Hymn #9 - Come, Rejoice', true, 9, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0010', 'Hymn #10 - Come, Sing to the Lord', true, 10, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0011', 'Hymn #11 - What Was Witnessed in the Heavens?', true, 11, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0012', 'Hymn #12 - ’Twas Witnessed in the Morning Sky', true, 12, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0013', 'Hymn #13 - An Angel from on High', true, 13, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0014', 'Hymn #14 - Sweet Is the Peace the Gospel Brings', true, 14, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0015', 'Hymn #15 - I Saw a Mighty Angel Fly', true, 15, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0016', 'Hymn #16 - What Glorious Scenes Mine Eyes Behold', true, 16, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0017', 'Hymn #17 - Awake, Ye Saints of God, Awake!', true, 17, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0018', 'Hymn #18 - The Voice of God Again Is Heard', true, 18, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0019', 'Hymn #19 - We Thank Thee, O God, for a Prophet', true, 19, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0020', 'Hymn #20 - God of Power, God of Right', true, 20, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0021', 'Hymn #21 - Come, Listen to a Prophet’s Voice', true, 21, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0022', 'Hymn #22 - We Listen to a Prophet’s Voice', true, 22, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0023', 'Hymn #23 - We Ever Pray for Thee', true, 23, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0024', 'Hymn #24 - God Bless Our Prophet Dear', true, 24, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0025', 'Hymn #25 - Now We’ll Sing with One Accord', true, 25, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0026', 'Hymn #26 - Joseph Smith’s First Prayer', true, 26, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0027', 'Hymn #27 - Praise to the Man', true, 27, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0028', 'Hymn #28 - Saints, Behold How Great Jehovah', true, 28, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0029', 'Hymn #29 - A Poor Wayfaring Man of Grief', true, 29, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0030', 'Hymn #30 - Come, Come, Ye Saints', true, 30, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0031', 'Hymn #31 - O God, Our Help in Ages Past', true, 31, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0032', 'Hymn #32 - The Happy Day at Last Has Come', true, 32, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0033', 'Hymn #33 - Our Mountain Home So Dear', true, 33, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0034', 'Hymn #34 - O Ye Mountains High', true, 34, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0035', 'Hymn #35 - For the Strength of the Hills', true, 35, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0036', 'Hymn #36 - They, the Builders of the Nation', true, 36, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0037', 'Hymn #37 - The Wintry Day, Descending to Its Close', true, 37, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0038', 'Hymn #38 - Come, All Ye Saints of Zion', true, 38, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0039', 'Hymn #39 - O Saints of Zion', true, 39, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0040', 'Hymn #40 - Arise, O Glorious Zion', true, 40, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0041', 'Hymn #41 - Let Zion in Her Beauty Rise', true, 41, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0042', 'Hymn #42 - Hail to the Brightness of Zion’s Glad Morning!', true, 42, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0043', 'Hymn #43 - Zion Stands with Hills Surrounded', true, 43, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0044', 'Hymn #44 - Beautiful Zion, Built Above', true, 44, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0045', 'Hymn #45 - Lead Me into Life Eternal', true, 45, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0046', 'Hymn #46 - Glorious Things of Thee Are Spoken', true, 46, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0047', 'Hymn #47 - We Will Sing of Zion', true, 47, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0048', 'Hymn #48 - Glorious Things Are Sung of Zion', true, 48, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0049', 'Hymn #49 - Adam-ondi-Ahman', true, 49, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0050', 'Hymn #50 - Come, Thou Glorious Day of Promise', true, 50, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0051', 'Hymn #51 - Sons of Michael, He Approaches', true, 51, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0052', 'Hymn #52 - The Day Dawn Is Breaking', true, 52, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0053', 'Hymn #53 - Let Earth’s Inhabitants Rejoice', true, 53, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0054', 'Hymn #54 - Behold, the Mountain of the Lord', true, 54, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0055', 'Hymn #55 - Lo, the Mighty God Appearing!', true, 55, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0056', 'Hymn #56 - Softly Beams the Sacred Dawning', true, 56, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0057', 'Hymn #57 - We’re Not Ashamed to Own Our Lord', true, 57, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0058', 'Hymn #58 - Come, Ye Children of the Lord', true, 58, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0059', 'Hymn #59 - Come, O Thou King of Kings', true, 59, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0060', 'Hymn #60 - Battle Hymn of the Republic', true, 60, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0061', 'Hymn #61 - Raise Your Voices to the Lord', true, 61, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0062', 'Hymn #62 - All Creatures of Our God and King', true, 62, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0063', 'Hymn #63 - Great King of Heaven', true, 63, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0064', 'Hymn #64 - On This Day of Joy and Gladness', true, 64, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0065', 'Hymn #65 - Come, All Ye Saints Who Dwell on Earth', true, 65, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0066', 'Hymn #66 - Rejoice, the Lord Is King!', true, 66, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0067', 'Hymn #67 - Glory to God on High', true, 67, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0068', 'Hymn #68 - A Mighty Fortress Is Our God', true, 68, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0069', 'Hymn #69 - All Glory, Laud, and Honor', true, 69, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0070', 'Hymn #70 - Sing Praise to Him', true, 70, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0071', 'Hymn #71 - With Songs of Praise', true, 71, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0072', 'Hymn #72 - Praise to the Lord, the Almighty', true, 72, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0073', 'Hymn #73 - Praise the Lord with Heart and Voice', true, 73, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0074', 'Hymn #74 - Praise Ye the Lord', true, 74, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0075', 'Hymn #75 - In Hymns of Praise', true, 75, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0076', 'Hymn #76 - God of Our Fathers, We Come unto Thee', true, 76, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0077', 'Hymn #77 - Great Is the Lord', true, 77, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0078', 'Hymn #78 - God of Our Fathers, Whose Almighty Hand', true, 78, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0079', 'Hymn #79 - With All the Power of Heart and Tongue', true, 79, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0080', 'Hymn #80 - God of Our Fathers, Known of Old', true, 80, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0081', 'Hymn #81 - Press Forward, Saints', true, 81, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0082', 'Hymn #82 - For All the Saints', true, 82, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0083', 'Hymn #83 - Guide Us, O Thou Great Jehovah', true, 83, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0084', 'Hymn #84 - Faith of Our Fathers', true, 84, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0085', 'Hymn #85 - How Firm a Foundation', true, 85, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0087', 'Hymn #87 - God Is Love', true, 87, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0088', 'Hymn #88 - Great God, Attend While Zion Sings', true, 88, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0089', 'Hymn #89 - The Lord Is My Light', true, 89, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0090', 'Hymn #90 - From All That Dwell below the Skies', true, 90, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0091', 'Hymn #91 - Father, Thy Children to Thee Now Raise', true, 91, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0092', 'Hymn #92 - For the Beauty of the Earth', true, 92, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0093', 'Hymn #93 - Prayer of Thanksgiving', true, 93, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0094', 'Hymn #94 - Come, Ye Thankful People', true, 94, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0095', 'Hymn #95 - Now Thank We All Our God', true, 95, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0096', 'Hymn #96 - Dearest Children, God Is Near You', true, 96, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0097', 'Hymn #97 - Lead, Kindly Light', true, 97, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0098', 'Hymn #98 - I Need Thee Every Hour', true, 98, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0099', 'Hymn #99 - Nearer, Dear Savior, to Thee', true, 99, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0100', 'Hymn #100 - Nearer, My God, to Thee', true, 100, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0101', 'Hymn #101 - Guide Me to Thee', true, 101, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0102', 'Hymn #102 - Jesus, Lover of My Soul', true, 102, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0103', 'Hymn #103 - Precious Savior, Dear Redeemer', true, 103, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0104', 'Hymn #104 - Jesus, Savior, Pilot Me', true, 104, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0105', 'Hymn #105 - Master, the Tempest Is Raging', true, 105, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0106', 'Hymn #106 - God Speed the Right', true, 106, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0107', 'Hymn #107 - Lord, Accept Our True Devotion', true, 107, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0108', 'Hymn #108 - The Lord Is My Shepherd', true, 108, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0109', 'Hymn #109 - The Lord My Pasture Will Prepare', true, 109, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0110', 'Hymn #110 - Cast Thy Burden upon the Lord', true, 110, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0111', 'Hymn #111 - Rock of Ages', true, 111, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0112', 'Hymn #112 - Savior, Redeemer of My Soul', true, 112, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0113', 'Hymn #113 - Our Savior’s Love', true, 113, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0114', 'Hymn #114 - Come unto Him', true, 114, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0115', 'Hymn #115 - Come, Ye Disconsolate', true, 115, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0116', 'Hymn #116 - Come, Follow Me', true, 116, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0117', 'Hymn #117 - Come unto Jesus', true, 117, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0118', 'Hymn #118 - Ye Simple Souls Who Stray', true, 118, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0119', 'Hymn #119 - Come, We That Love the Lord', true, 119, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0120', 'Hymn #120 - Lean on My Ample Arm', true, 120, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0121', 'Hymn #121 - I’m a Pilgrim, I’m a Stranger', true, 121, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0122', 'Hymn #122 - Though Deepening Trials', true, 122, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0123', 'Hymn #123 - Oh, May My Soul Commune with Thee', true, 123, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0124', 'Hymn #124 - Be Still, My Soul', true, 124, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0125', 'Hymn #125 - How Gentle God’s Commands', true, 125, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0126', 'Hymn #126 - How Long, O Lord Most Holy and True', true, 126, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0127', 'Hymn #127 - Does the Journey Seem Long?', true, 127, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0128', 'Hymn #128 - When Faith Endures', true, 128, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0129', 'Hymn #129 - Where Can I Turn for Peace?', true, 129, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0130', 'Hymn #130 - Be Thou Humble', true, 130, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0131', 'Hymn #131 - More Holiness Give Me', true, 131, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0132', 'Hymn #132 - God Is in His Holy Temple', true, 132, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0133', 'Hymn #133 - Father in Heaven', true, 133, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0134', 'Hymn #134 - I Believe in Christ', true, 134, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0135', 'Hymn #135 - My Redeemer Lives', true, 135, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0136', 'Hymn #136 - I Know That My Redeemer Lives', true, 136, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0137', 'Hymn #137 - Testimony', true, 137, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0138', 'Hymn #138 - Bless Our Fast, We Pray', true, 138, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0139', 'Hymn #139 - In Fasting We Approach Thee', true, 139, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0140', 'Hymn #140 - Did You Think to Pray?', true, 140, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0141', 'Hymn #141 - Jesus, the Very Thought of Thee', true, 141, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0142', 'Hymn #142 - Sweet Hour of Prayer', true, 142, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0143', 'Hymn #143 - Let the Holy Spirit Guide', true, 143, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0144', 'Hymn #144 - Secret Prayer', true, 144, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0145', 'Hymn #145 - Prayer Is the Soul’s Sincere Desire', true, 145, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0146', 'Hymn #146 - Gently Raise the Sacred Strain', true, 146, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0147', 'Hymn #147 - Sweet Is the Work', true, 147, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0148', 'Hymn #148 - Sabbath Day', true, 148, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0149', 'Hymn #149 - As the Dew from Heaven Distilling', true, 149, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0150', 'Hymn #150 - O Thou Kind and Gracious Father', true, 150, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0151', 'Hymn #151 - We Meet, Dear Lord', true, 151, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0152', 'Hymn #152 - God Be with You Till We Meet Again', true, 152, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0153', 'Hymn #153 - Lord, We Ask Thee Ere We Part', true, 153, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0154', 'Hymn #154 - Father, This Hour Has Been One of Joy', true, 154, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0155', 'Hymn #155 - We Have Partaken of Thy Love', true, 155, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0156', 'Hymn #156 - Sing We Now at Parting', true, 156, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0157', 'Hymn #157 - Thy Spirit, Lord, Has Stirred Our Souls', true, 157, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0158', 'Hymn #158 - Before Thee, Lord, I Bow My Head', true, 158, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0159', 'Hymn #159 - Now the Day Is Over', true, 159, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0160', 'Hymn #160 - Softly Now the Light of Day', true, 160, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0161', 'Hymn #161 - The Lord Be with Us', true, 161, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0162', 'Hymn #162 - Lord, We Come before Thee Now', true, 162, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0163', 'Hymn #163 - Lord, Dismiss Us with Thy Blessing', true, 163, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0164', 'Hymn #164 - Great God, to Thee My Evening Song', true, 164, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0165', 'Hymn #165 - Abide with Me; ’Tis Eventide', true, 165, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0166', 'Hymn #166 - Abide with Me!', true, 166, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0167', 'Hymn #167 - Come, Let Us Sing an Evening Hymn', true, 167, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0168', 'Hymn #168 - As the Shadows Fall', true, 168, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0169', 'Hymn #169 - As Now We Take the Sacrament', true, 169, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0170', 'Hymn #170 - God, Our Father, Hear Us Pray', true, 170, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0171', 'Hymn #171 - With Humble Heart', true, 171, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0172', 'Hymn #172 - In Humility, Our Savior', true, 172, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0173', 'Hymn #173 - While of These Emblems We Partake', true, 173, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0174', 'Hymn #174 - While of These Emblems We Partake', true, 174, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0175', 'Hymn #175 - O God, the Eternal Father', true, 175, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0176', 'Hymn #176 - ’Tis Sweet to Sing the Matchless Love', true, 176, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0177', 'Hymn #177 - ’Tis Sweet to Sing the Matchless Love', true, 177, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0178', 'Hymn #178 - O Lord of Hosts', true, 178, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0179', 'Hymn #179 - Again, Our Dear Redeeming Lord', true, 179, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0180', 'Hymn #180 - Father in Heaven, We Do Believe', true, 180, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0181', 'Hymn #181 - Jesus of Nazareth, Savior and King', true, 181, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0182', 'Hymn #182 - We’ll Sing All Hail to Jesus’ Name', true, 182, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0183', 'Hymn #183 - In Remembrance of Thy Suffering', true, 183, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0184', 'Hymn #184 - Upon the Cross of Calvary', true, 184, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0185', 'Hymn #185 - Reverently and Meekly Now', true, 185, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0186', 'Hymn #186 - Again We Meet around the Board', true, 186, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0187', 'Hymn #187 - God Loved Us, So He Sent His Son', true, 187, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0188', 'Hymn #188 - Thy Will, O Lord, Be Done', true, 188, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0189', 'Hymn #189 - O Thou, Before the World Began', true, 189, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0190', 'Hymn #190 - In Memory of the Crucified', true, 190, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0191', 'Hymn #191 - Behold the Great Redeemer Die', true, 191, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0192', 'Hymn #192 - He Died! The Great Redeemer Died', true, 192, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0193', 'Hymn #193 - I Stand All Amazed', true, 193, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0194', 'Hymn #194 - There Is a Green Hill Far Away', true, 194, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0195', 'Hymn #195 - How Great the Wisdom and the Love', true, 195, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0196', 'Hymn #196 - Jesus, Once of Humble Birth', true, 196, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0197', 'Hymn #197 - O Savior, Thou Who Wearest a Crown', true, 197, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0198', 'Hymn #198 - That Easter Morn', true, 198, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0199', 'Hymn #199 - He Is Risen!', true, 199, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0200', 'Hymn #200 - Christ the Lord Is Risen Today', true, 200, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0201', 'Hymn #201 - Joy to the World', true, 201, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0202', 'Hymn #202 - Oh, Come, All Ye Faithful', true, 202, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0203', 'Hymn #203 - Angels We Have Heard on High', true, 203, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0204', 'Hymn #204 - Silent Night', true, 204, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0205', 'Hymn #205 - Once in Royal David’s City', true, 205, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0206', 'Hymn #206 - Away in a Manger', true, 206, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0207', 'Hymn #207 - It Came upon the Midnight Clear', true, 207, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0208', 'Hymn #208 - O Little Town of Bethlehem', true, 208, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0209', 'Hymn #209 - Hark! The Herald Angels Sing', true, 209, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0210', 'Hymn #210 - With Wondering Awe', true, 210, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0211', 'Hymn #211 - While Shepherds Watched Their Flocks', true, 211, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0212', 'Hymn #212 - Far, Far Away on Judea’s Plains', true, 212, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0213', 'Hymn #213 - The First Noel', true, 213, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0214', 'Hymn #214 - I Heard the Bells on Christmas Day', true, 214, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0215', 'Hymn #215 - Ring Out, Wild Bells', true, 215, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0216', 'Hymn #216 - We Are Sowing', true, 216, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0217', 'Hymn #217 - Come, Let Us Anew', true, 217, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0218', 'Hymn #218 - We Give Thee But Thine Own', true, 218, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0220', 'Hymn #220 - Lord, I Would Follow Thee', true, 220, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0221', 'Hymn #221 - Dear to the Heart of the Shepherd', true, 221, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0222', 'Hymn #222 - Hear Thou Our Hymn, O Lord', true, 222, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0223', 'Hymn #223 - Have I Done Any Good?', true, 223, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0224', 'Hymn #224 - I Have Work Enough to Do', true, 224, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0225', 'Hymn #225 - We Are Marching On to Glory', true, 225, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0226', 'Hymn #226 - Improve the Shining Moments', true, 226, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0227', 'Hymn #227 - There Is Sunshine in My Soul Today', true, 227, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0228', 'Hymn #228 - You Can Make the Pathway Bright', true, 228, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0229', 'Hymn #229 - Today, While the Sun Shines', true, 229, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0230', 'Hymn #230 - Scatter Sunshine', true, 230, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0231', 'Hymn #231 - Father, Cheer Our Souls Tonight', true, 231, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0232', 'Hymn #232 - Let Us Oft Speak Kind Words', true, 232, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0233', 'Hymn #233 - Nay, Speak No Ill', true, 233, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0234', 'Hymn #234 - Jesus, Mighty King in Zion', true, 234, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0235', 'Hymn #235 - Should You Feel Inclined to Censure', true, 235, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0236', 'Hymn #236 - Lord, Accept into Thy Kingdom', true, 236, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0237', 'Hymn #237 - Do What Is Right', true, 237, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0238', 'Hymn #238 - Behold Thy Sons and Daughters, Lord', true, 238, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0239', 'Hymn #239 - Choose the Right', true, 239, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0240', 'Hymn #240 - Know This, That Every Soul Is Free', true, 240, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0241', 'Hymn #241 - Count Your Blessings', true, 241, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0242', 'Hymn #242 - Praise God, from Whom All Blessings Flow', true, 242, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0243', 'Hymn #243 - Let Us All Press On', true, 243, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0244', 'Hymn #244 - Come Along, Come Along', true, 244, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0245', 'Hymn #245 - This House We Dedicate to Thee', true, 245, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0246', 'Hymn #246 - Onward, Christian Soldiers', true, 246, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0247', 'Hymn #247 - We Love Thy House, O God', true, 247, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0248', 'Hymn #248 - Up, Awake, Ye Defenders of Zion', true, 248, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0249', 'Hymn #249 - Called to Serve', true, 249, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0250', 'Hymn #250 - We Are All Enlisted', true, 250, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0251', 'Hymn #251 - Behold! A Royal Army', true, 251, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0252', 'Hymn #252 - Put Your Shoulder to the Wheel', true, 252, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0253', 'Hymn #253 - Like Ten Thousand Legions Marching', true, 253, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0254', 'Hymn #254 - True to the Faith', true, 254, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0255', 'Hymn #255 - Carry On', true, 255, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0256', 'Hymn #256 - As Zion’s Youth in Latter Days', true, 256, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0257', 'Hymn #257 - Rejoice! A Glorious Sound Is Heard', true, 257, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0258', 'Hymn #258 - O Thou Rock of Our Salvation', true, 258, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0259', 'Hymn #259 - Hope of Israel', true, 259, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0260', 'Hymn #260 - Who’s on the Lord’s Side?', true, 260, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0261', 'Hymn #261 - Thy Servants Are Prepared', true, 261, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0262', 'Hymn #262 - Go, Ye Messengers of Glory', true, 262, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0263', 'Hymn #263 - Go Forth with Faith', true, 263, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0264', 'Hymn #264 - Hark, All Ye Nations!', true, 264, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0265', 'Hymn #265 - Arise, O God, and Shine', true, 265, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0266', 'Hymn #266 - The Time Is Far Spent', true, 266, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0267', 'Hymn #267 - How Wondrous and Great', true, 267, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0268', 'Hymn #268 - Come, All Whose Souls Are Lighted', true, 268, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0269', 'Hymn #269 - Jehovah, Lord of Heaven and Earth', true, 269, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0270', 'Hymn #270 - I’ll Go Where You Want Me to Go', true, 270, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0271', 'Hymn #271 - Oh, Holy Words of Truth and Love', true, 271, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0272', 'Hymn #272 - Oh Say, What Is Truth?', true, 272, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0273', 'Hymn #273 - Truth Reflects upon Our Senses', true, 273, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0274', 'Hymn #274 - The Iron Rod', true, 274, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0275', 'Hymn #275 - Men Are That They Might Have Joy', true, 275, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0276', 'Hymn #276 - Come Away to the Sunday School', true, 276, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0277', 'Hymn #277 - As I Search the Holy Scriptures', true, 277, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0278', 'Hymn #278 - Thanks for the Sabbath School', true, 278, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0279', 'Hymn #279 - Thy Holy Word', true, 279, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0280', 'Hymn #280 - Welcome, Welcome, Sabbath Morning', true, 280, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0281', 'Hymn #281 - Help Me Teach with Inspiration', true, 281, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0282', 'Hymn #282 - We Meet Again in Sabbath School', true, 282, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0283', 'Hymn #283 - The Glorious Gospel Light Has Shone', true, 283, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0284', 'Hymn #284 - If You Could Hie to Kolob', true, 284, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0285', 'Hymn #285 - God Moves in a Mysterious Way', true, 285, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0286', 'Hymn #286 - Oh, What Songs of the Heart', true, 286, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0287', 'Hymn #287 - Rise, Ye Saints, and Temples Enter', true, 287, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0288', 'Hymn #288 - How Beautiful Thy Temples, Lord', true, 288, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0289', 'Hymn #289 - Holy Temples on Mount Zion', true, 289, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0290', 'Hymn #290 - Rejoice, Ye Saints of Latter Days', true, 290, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0291', 'Hymn #291 - Turn Your Hearts', true, 291, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0292', 'Hymn #292 - O My Father', true, 292, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0293', 'Hymn #293 - Each Life That Touches Ours for Good', true, 293, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0294', 'Hymn #294 - Love at Home', true, 294, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0295', 'Hymn #295 - O Love That Glorifies the Son', true, 295, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0296', 'Hymn #296 - Our Father, by Whose Name', true, 296, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0297', 'Hymn #297 - From Homes of Saints Glad Songs Arise', true, 297, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0298', 'Hymn #298 - Home Can Be a Heaven on Earth', true, 298, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0300', 'Hymn #300 - Families Can Be Together Forever', true, 300, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0301', 'Hymn #301 - I Am a Child of God', true, 301, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0302', 'Hymn #302 - I Know My Father Lives', true, 302, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0303', 'Hymn #303 - Keep the Commandments', true, 303, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0304', 'Hymn #304 - Teach Me to Walk in the Light', true, 304, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0305', 'Hymn #305 - The Light Divine', true, 305, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0306', 'Hymn #306 - God’s Daily Care', true, 306, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0307', 'Hymn #307 - In Our Lovely Deseret', true, 307, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0308', 'Hymn #308 - Love One Another', true, 308, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0309', 'Hymn #309 - As Sisters in Zion', true, 309, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0310', 'Hymn #310 - A Key Was Turned in Latter Days', true, 310, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0311', 'Hymn #311 - We Meet Again as Sisters', true, 311, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0312', 'Hymn #312 - We Ever Pray for Thee', true, 312, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0313', 'Hymn #313 - God Is Love', true, 313, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0314', 'Hymn #314 - How Gentle God’s Commands', true, 314, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0315', 'Hymn #315 - Jesus, the Very Thought of Thee', true, 315, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0316', 'Hymn #316 - The Lord Is My Shepherd', true, 316, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0317', 'Hymn #317 - Sweet Is the Work', true, 317, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0318', 'Hymn #318 - Love at Home', true, 318, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0319', 'Hymn #319 - Ye Elders of Israel', true, 319, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0320', 'Hymn #320 - The Priesthood of Our Lord', true, 320, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0321', 'Hymn #321 - Ye Who Are Called to Labor', true, 321, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0322', 'Hymn #322 - Come, All Ye Sons of God', true, 322, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0323', 'Hymn #323 - Rise Up, O Men of God', true, 323, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0324', 'Hymn #324 - Rise Up, O Men of God', true, 324, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0325', 'Hymn #325 - See the Mighty Priesthood Gathered', true, 325, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0326', 'Hymn #326 - Come, Come, Ye Saints', true, 326, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0327', 'Hymn #327 - Go, Ye Messengers of Heaven', true, 327, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0328', 'Hymn #328 - An Angel from on High', true, 328, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0329', 'Hymn #329 - Thy Servants Are Prepared', true, 329, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0330', 'Hymn #330 - See, the Mighty Angel Flying', true, 330, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0331', 'Hymn #331 - Oh Say, What Is Truth?', true, 331, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0332', 'Hymn #332 - Come, O Thou King of Kings', true, 332, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0333', 'Hymn #333 - High on the Mountain Top', true, 333, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0334', 'Hymn #334 - I Need Thee Every Hour', true, 334, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0335', 'Hymn #335 - Brightly Beams Our Father’s Mercy', true, 335, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0336', 'Hymn #336 - School Thy Feelings', true, 336, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0337', 'Hymn #337 - O Home Beloved', true, 337, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0338', 'Hymn #338 - America the Beautiful', true, 338, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0339', 'Hymn #339 - My Country, ’Tis of Thee', true, 339, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0340', 'Hymn #340 - The Star-Spangled Banner', true, 340, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_0341', 'Hymn #341 - God Save the King', true, 341, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1001', 'Hymn #1001 - Come, Thou Fount of Every Blessing', true, 1001, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1002', 'Hymn #1002 - When the Savior Comes Again', true, 1002, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1003', 'Hymn #1003 - It Is Well with My Soul', true, 1003, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1004', 'Hymn #1004 - I Will Walk with Jesus', true, 1004, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1005', 'Hymn #1005 - His Eye Is on the Sparrow', true, 1005, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1006', 'Hymn #1006 - Think a Sacred Song', true, 1006, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1007', 'Hymn #1007 - As Bread Is Broken', true, 1007, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1008', 'Hymn #1008 - Bread of Life, Living Water', true, 1008, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1009', 'Hymn #1009 - Gethsemane', true, 1009, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1010', 'Hymn #1010 - Amazing Grace', true, 1010, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1011', 'Hymn #1011 - Holding Hands Around the World', true, 1011, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1012', 'Hymn #1012 - Anytime, Anywhere', true, 1012, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1013', 'Hymn #1013 - God’s Gracious Love', true, 1013, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1014', 'Hymn #1014 - My Shepherd Will Supply My Need', true, 1014, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1015', 'Hymn #1015 - Oh, the Deep, Deep Love of Jesus', true, 1015, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1016', 'Hymn #1016 - Behold the Wounds in Jesus’ Hands', true, 1016, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1017', 'Hymn #1017 - This Is the Christ', true, 1017, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1018', 'Hymn #1018 - Come, Lord Jesus', true, 1018, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1019', 'Hymn #1019 - To Love like Thee', true, 1019, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1020', 'Hymn #1020 - Softly and Tenderly Jesus Is Calling', true, 1020, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1021', 'Hymn #1021 - I Know That My Savior Loves Me', true, 1021, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1022', 'Hymn #1022 - Faith in Every Footstep', true, 1022, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1023', 'Hymn #1023 - Standing on the Promises', true, 1023, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1024', 'Hymn #1024 - I Have Faith in the Lord Jesus Christ', true, 1024, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1025', 'Hymn #1025 - Take My Heart and Let It Be Consecrated', true, 1025, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1026', 'Hymn #1026 - Holy Places', true, 1026, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1027', 'Hymn #1027 - Welcome Home', true, 1027, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1028', 'Hymn #1028 - This Little Light of Mine', true, 1028, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1029', 'Hymn #1029 - I Can’t Count Them All', true, 1029, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1030', 'Hymn #1030 - Close as a Quiet Prayer', true, 1030, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1031', 'Hymn #1031 - Come, Hear the Word the Lord Has Spoken', true, 1031, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1032', 'Hymn #1032 - Look unto Christ', true, 1032, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1033', 'Hymn #1033 - Oh, How Great Is Our Joy', true, 1033, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1034', 'Hymn #1034 - I’m a Pioneer Too', true, 1034, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1035', 'Hymn #1035 - As I Keep the Sabbath Day', true, 1035, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1036', 'Hymn #1036 - Read the Book of Mormon and Pray', true, 1036, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1037', 'Hymn #1037 - I’m Gonna Live So God Can Use Me', true, 1037, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1038', 'Hymn #1038 - The Lord’s My Shepherd', true, 1038, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1039', 'Hymn #1039 - Because', true, 1039, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1040', 'Hymn #1040 - His Voice as the Sound', true, 1040, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1041', 'Hymn #1041 - O Lord, Who Gave Thy Life for Me', true, 1041, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1042', 'Hymn #1042 - Thou Gracious God, Whose Mercy Lends', true, 1042, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1043', 'Hymn #1043 - Help Us Remember', true, 1043, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1044', 'Hymn #1044 - How Did the Savior Minister?', true, 1044, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1045', 'Hymn #1045 - Jesus Is the Way', true, 1045, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1046', 'Hymn #1046 - Can You Count the Stars in Heaven?', true, 1046, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1047', 'Hymn #1047 - He Cares for Me', true, 1047, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1048', 'Hymn #1048 - Our Prayer to Thee', true, 1048, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1049', 'Hymn #1049 - Joseph Prayed in Faith', true, 1049, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1050', 'Hymn #1050 - Stand by Me', true, 1050, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1051', 'Hymn #1051 - This Day Is a Good Day, Lord', true, 1051, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1201', 'Hymn #1201 - Hail the Day That Sees Him Rise', true, 1201, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1202', 'Hymn #1202 - He Is Born, the Divine Christ Child', true, 1202, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1203', 'Hymn #1203 - What Child Is This?', true, 1203, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1204', 'Hymn #1204 - Star Bright', true, 1204, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1205', 'Hymn #1205 - Let Easter Anthems Ring', true, 1205, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1206', 'Hymn #1206 - Were You There?', true, 1206, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1207', 'Hymn #1207 - Still, Still, Still', true, 1207, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1208', 'Hymn #1208 - Go Tell It on the Mountain', true, 1208, 3, 15);
INSERT INTO procedural_item_types (id, name, is_hymn, hymn_number, default_duration_minutes, order_hint) VALUES ('hymn_1209', 'Hymn #1209 - Little Baby in a Manger', true, 1209, 3, 15);
