-- Generated 398 hymns
-- Note: IDs are auto-generated. Lyrics are excluded.
INSERT INTO hymns (book_id, hymn_number, title) VALUES
('hymns_church', 1, 'The Morning Breaks'),
('hymns_church', 2, 'The Spirit of God'),
('hymns_church', 3, 'Now Let Us Rejoice'),
('hymns_church', 4, 'Truth Eternal'),
('hymns_church', 5, 'High on the Mountain Top'),
('hymns_church', 6, 'Redeemer of Israel'),
('hymns_church', 7, 'Israel, Israel, God Is Calling'),
('hymns_church', 8, 'Awake and Arise'),
('hymns_church', 9, 'Come, Rejoice'),
('hymns_church', 10, 'Come, Sing to the Lord'),
('hymns_church', 11, 'What Was Witnessed in the Heavens?'),
('hymns_church', 12, '’Twas Witnessed in the Morning Sky'),
('hymns_church', 13, 'An Angel from on High'),
('hymns_church', 14, 'Sweet Is the Peace the Gospel Brings'),
('hymns_church', 15, 'I Saw a Mighty Angel Fly'),
('hymns_church', 16, 'What Glorious Scenes Mine Eyes Behold'),
('hymns_church', 17, 'Awake, Ye Saints of God, Awake!'),
('hymns_church', 18, 'The Voice of God Again Is Heard'),
('hymns_church', 19, 'We Thank Thee, O God, for a Prophet'),
('hymns_church', 20, 'God of Power, God of Right'),
('hymns_church', 21, 'Come, Listen to a Prophet’s Voice'),
('hymns_church', 22, 'We Listen to a Prophet’s Voice'),
('hymns_church', 23, 'We Ever Pray for Thee'),
('hymns_church', 24, 'God Bless Our Prophet Dear'),
('hymns_church', 25, 'Now We’ll Sing with One Accord'),
('hymns_church', 26, 'Joseph Smith’s First Prayer'),
('hymns_church', 27, 'Praise to the Man'),
('hymns_church', 28, 'Saints, Behold How Great Jehovah'),
('hymns_church', 29, 'A Poor Wayfaring Man of Grief'),
('hymns_church', 30, 'Come, Come, Ye Saints'),
('hymns_church', 31, 'O God, Our Help in Ages Past'),
('hymns_church', 32, 'The Happy Day at Last Has Come'),
('hymns_church', 33, 'Our Mountain Home So Dear'),
('hymns_church', 34, 'O Ye Mountains High'),
('hymns_church', 35, 'For the Strength of the Hills'),
('hymns_church', 36, 'They, the Builders of the Nation'),
('hymns_church', 37, 'The Wintry Day, Descending to Its Close'),
('hymns_church', 38, 'Come, All Ye Saints of Zion'),
('hymns_church', 39, 'O Saints of Zion'),
('hymns_church', 40, 'Arise, O Glorious Zion'),
('hymns_church', 41, 'Let Zion in Her Beauty Rise'),
('hymns_church', 42, 'Hail to the Brightness of Zion’s Glad Morning!'),
('hymns_church', 43, 'Zion Stands with Hills Surrounded'),
('hymns_church', 44, 'Beautiful Zion, Built Above'),
('hymns_church', 45, 'Lead Me into Life Eternal'),
('hymns_church', 46, 'Glorious Things of Thee Are Spoken'),
('hymns_church', 47, 'We Will Sing of Zion'),
('hymns_church', 48, 'Glorious Things Are Sung of Zion'),
('hymns_church', 49, 'Adam-ondi-Ahman'),
('hymns_church', 50, 'Come, Thou Glorious Day of Promise'),
('hymns_church', 51, 'Sons of Michael, He Approaches'),
('hymns_church', 52, 'The Day Dawn Is Breaking'),
('hymns_church', 53, 'Let Earth’s Inhabitants Rejoice'),
('hymns_church', 54, 'Behold, the Mountain of the Lord'),
('hymns_church', 55, 'Lo, the Mighty God Appearing!'),
('hymns_church', 56, 'Softly Beams the Sacred Dawning'),
('hymns_church', 57, 'We’re Not Ashamed to Own Our Lord'),
('hymns_church', 58, 'Come, Ye Children of the Lord'),
('hymns_church', 59, 'Come, O Thou King of Kings'),
('hymns_church', 60, 'Battle Hymn of the Republic'),
('hymns_church', 61, 'Raise Your Voices to the Lord'),
('hymns_church', 62, 'All Creatures of Our God and King'),
('hymns_church', 63, 'Great King of Heaven'),
('hymns_church', 64, 'On This Day of Joy and Gladness'),
('hymns_church', 65, 'Come, All Ye Saints Who Dwell on Earth'),
('hymns_church', 66, 'Rejoice, the Lord Is King!'),
('hymns_church', 67, 'Glory to God on High'),
('hymns_church', 68, 'A Mighty Fortress Is Our God'),
('hymns_church', 69, 'All Glory, Laud, and Honor'),
('hymns_church', 70, 'Sing Praise to Him'),
('hymns_church', 71, 'With Songs of Praise'),
('hymns_church', 72, 'Praise to the Lord, the Almighty'),
('hymns_church', 73, 'Praise the Lord with Heart and Voice'),
('hymns_church', 74, 'Praise Ye the Lord'),
('hymns_church', 75, 'In Hymns of Praise'),
('hymns_church', 76, 'God of Our Fathers, We Come unto Thee'),
('hymns_church', 77, 'Great Is the Lord'),
('hymns_church', 78, 'God of Our Fathers, Whose Almighty Hand'),
('hymns_church', 79, 'With All the Power of Heart and Tongue'),
('hymns_church', 80, 'God of Our Fathers, Known of Old'),
('hymns_church', 81, 'Press Forward, Saints'),
('hymns_church', 82, 'For All the Saints'),
('hymns_church', 83, 'Guide Us, O Thou Great Jehovah'),
('hymns_church', 84, 'Faith of Our Fathers'),
('hymns_church', 85, 'How Firm a Foundation'),
('hymns_church', 87, 'God Is Love'),
('hymns_church', 88, 'Great God, Attend While Zion Sings'),
('hymns_church', 89, 'The Lord Is My Light'),
('hymns_church', 90, 'From All That Dwell below the Skies'),
('hymns_church', 91, 'Father, Thy Children to Thee Now Raise'),
('hymns_church', 92, 'For the Beauty of the Earth'),
('hymns_church', 93, 'Prayer of Thanksgiving'),
('hymns_church', 94, 'Come, Ye Thankful People'),
('hymns_church', 95, 'Now Thank We All Our God'),
('hymns_church', 96, 'Dearest Children, God Is Near You'),
('hymns_church', 97, 'Lead, Kindly Light'),
('hymns_church', 98, 'I Need Thee Every Hour'),
('hymns_church', 99, 'Nearer, Dear Savior, to Thee'),
('hymns_church', 100, 'Nearer, My God, to Thee'),
('hymns_church', 101, 'Guide Me to Thee'),
('hymns_church', 102, 'Jesus, Lover of My Soul'),
('hymns_church', 103, 'Precious Savior, Dear Redeemer'),
('hymns_church', 104, 'Jesus, Savior, Pilot Me'),
('hymns_church', 105, 'Master, the Tempest Is Raging'),
('hymns_church', 106, 'God Speed the Right'),
('hymns_church', 107, 'Lord, Accept Our True Devotion'),
('hymns_church', 108, 'The Lord Is My Shepherd'),
('hymns_church', 109, 'The Lord My Pasture Will Prepare'),
('hymns_church', 110, 'Cast Thy Burden upon the Lord'),
('hymns_church', 111, 'Rock of Ages'),
('hymns_church', 112, 'Savior, Redeemer of My Soul'),
('hymns_church', 113, 'Our Savior’s Love'),
('hymns_church', 114, 'Come unto Him'),
('hymns_church', 115, 'Come, Ye Disconsolate'),
('hymns_church', 116, 'Come, Follow Me'),
('hymns_church', 117, 'Come unto Jesus'),
('hymns_church', 118, 'Ye Simple Souls Who Stray'),
('hymns_church', 119, 'Come, We That Love the Lord'),
('hymns_church', 120, 'Lean on My Ample Arm'),
('hymns_church', 121, 'I’m a Pilgrim, I’m a Stranger'),
('hymns_church', 122, 'Though Deepening Trials'),
('hymns_church', 123, 'Oh, May My Soul Commune with Thee'),
('hymns_church', 124, 'Be Still, My Soul'),
('hymns_church', 125, 'How Gentle God’s Commands'),
('hymns_church', 126, 'How Long, O Lord Most Holy and True'),
('hymns_church', 127, 'Does the Journey Seem Long?'),
('hymns_church', 128, 'When Faith Endures'),
('hymns_church', 129, 'Where Can I Turn for Peace?'),
('hymns_church', 130, 'Be Thou Humble'),
('hymns_church', 131, 'More Holiness Give Me'),
('hymns_church', 132, 'God Is in His Holy Temple'),
('hymns_church', 133, 'Father in Heaven'),
('hymns_church', 134, 'I Believe in Christ'),
('hymns_church', 135, 'My Redeemer Lives'),
('hymns_church', 136, 'I Know That My Redeemer Lives'),
('hymns_church', 137, 'Testimony'),
('hymns_church', 138, 'Bless Our Fast, We Pray'),
('hymns_church', 139, 'In Fasting We Approach Thee'),
('hymns_church', 140, 'Did You Think to Pray?'),
('hymns_church', 141, 'Jesus, the Very Thought of Thee'),
('hymns_church', 142, 'Sweet Hour of Prayer'),
('hymns_church', 143, 'Let the Holy Spirit Guide'),
('hymns_church', 144, 'Secret Prayer'),
('hymns_church', 145, 'Prayer Is the Soul’s Sincere Desire'),
('hymns_church', 146, 'Gently Raise the Sacred Strain'),
('hymns_church', 147, 'Sweet Is the Work'),
('hymns_church', 148, 'Sabbath Day'),
('hymns_church', 149, 'As the Dew from Heaven Distilling'),
('hymns_church', 150, 'O Thou Kind and Gracious Father'),
('hymns_church', 151, 'We Meet, Dear Lord'),
('hymns_church', 152, 'God Be with You Till We Meet Again'),
('hymns_church', 153, 'Lord, We Ask Thee Ere We Part'),
('hymns_church', 154, 'Father, This Hour Has Been One of Joy'),
('hymns_church', 155, 'We Have Partaken of Thy Love'),
('hymns_church', 156, 'Sing We Now at Parting'),
('hymns_church', 157, 'Thy Spirit, Lord, Has Stirred Our Souls'),
('hymns_church', 158, 'Before Thee, Lord, I Bow My Head'),
('hymns_church', 159, 'Now the Day Is Over'),
('hymns_church', 160, 'Softly Now the Light of Day'),
('hymns_church', 161, 'The Lord Be with Us'),
('hymns_church', 162, 'Lord, We Come before Thee Now'),
('hymns_church', 163, 'Lord, Dismiss Us with Thy Blessing'),
('hymns_church', 164, 'Great God, to Thee My Evening Song'),
('hymns_church', 165, 'Abide with Me; ’Tis Eventide'),
('hymns_church', 166, 'Abide with Me!'),
('hymns_church', 167, 'Come, Let Us Sing an Evening Hymn'),
('hymns_church', 168, 'As the Shadows Fall'),
('hymns_church', 169, 'As Now We Take the Sacrament'),
('hymns_church', 170, 'God, Our Father, Hear Us Pray'),
('hymns_church', 171, 'With Humble Heart'),
('hymns_church', 172, 'In Humility, Our Savior'),
('hymns_church', 173, 'While of These Emblems We Partake'),
('hymns_church', 174, 'While of These Emblems We Partake'),
('hymns_church', 175, 'O God, the Eternal Father'),
('hymns_church', 176, '’Tis Sweet to Sing the Matchless Love'),
('hymns_church', 177, '’Tis Sweet to Sing the Matchless Love'),
('hymns_church', 178, 'O Lord of Hosts'),
('hymns_church', 179, 'Again, Our Dear Redeeming Lord'),
('hymns_church', 180, 'Father in Heaven, We Do Believe'),
('hymns_church', 181, 'Jesus of Nazareth, Savior and King'),
('hymns_church', 182, 'We’ll Sing All Hail to Jesus’ Name'),
('hymns_church', 183, 'In Remembrance of Thy Suffering'),
('hymns_church', 184, 'Upon the Cross of Calvary'),
('hymns_church', 185, 'Reverently and Meekly Now'),
('hymns_church', 186, 'Again We Meet around the Board'),
('hymns_church', 187, 'God Loved Us, So He Sent His Son'),
('hymns_church', 188, 'Thy Will, O Lord, Be Done'),
('hymns_church', 189, 'O Thou, Before the World Began'),
('hymns_church', 190, 'In Memory of the Crucified'),
('hymns_church', 191, 'Behold the Great Redeemer Die'),
('hymns_church', 192, 'He Died! The Great Redeemer Died'),
('hymns_church', 193, 'I Stand All Amazed'),
('hymns_church', 194, 'There Is a Green Hill Far Away'),
('hymns_church', 195, 'How Great the Wisdom and the Love'),
('hymns_church', 196, 'Jesus, Once of Humble Birth'),
('hymns_church', 197, 'O Savior, Thou Who Wearest a Crown'),
('hymns_church', 198, 'That Easter Morn'),
('hymns_church', 199, 'He Is Risen!'),
('hymns_church', 200, 'Christ the Lord Is Risen Today'),
('hymns_church', 201, 'Joy to the World'),
('hymns_church', 202, 'Oh, Come, All Ye Faithful'),
('hymns_church', 203, 'Angels We Have Heard on High'),
('hymns_church', 204, 'Silent Night'),
('hymns_church', 205, 'Once in Royal David’s City'),
('hymns_church', 206, 'Away in a Manger'),
('hymns_church', 207, 'It Came upon the Midnight Clear'),
('hymns_church', 208, 'O Little Town of Bethlehem'),
('hymns_church', 209, 'Hark! The Herald Angels Sing'),
('hymns_church', 210, 'With Wondering Awe'),
('hymns_church', 211, 'While Shepherds Watched Their Flocks'),
('hymns_church', 212, 'Far, Far Away on Judea’s Plains'),
('hymns_church', 213, 'The First Noel'),
('hymns_church', 214, 'I Heard the Bells on Christmas Day'),
('hymns_church', 215, 'Ring Out, Wild Bells'),
('hymns_church', 216, 'We Are Sowing'),
('hymns_church', 217, 'Come, Let Us Anew'),
('hymns_church', 218, 'We Give Thee But Thine Own'),
('hymns_church', 220, 'Lord, I Would Follow Thee'),
('hymns_church', 221, 'Dear to the Heart of the Shepherd'),
('hymns_church', 222, 'Hear Thou Our Hymn, O Lord'),
('hymns_church', 223, 'Have I Done Any Good?'),
('hymns_church', 224, 'I Have Work Enough to Do'),
('hymns_church', 225, 'We Are Marching On to Glory'),
('hymns_church', 226, 'Improve the Shining Moments'),
('hymns_church', 227, 'There Is Sunshine in My Soul Today'),
('hymns_church', 228, 'You Can Make the Pathway Bright'),
('hymns_church', 229, 'Today, While the Sun Shines'),
('hymns_church', 230, 'Scatter Sunshine'),
('hymns_church', 231, 'Father, Cheer Our Souls Tonight'),
('hymns_church', 232, 'Let Us Oft Speak Kind Words'),
('hymns_church', 233, 'Nay, Speak No Ill'),
('hymns_church', 234, 'Jesus, Mighty King in Zion'),
('hymns_church', 235, 'Should You Feel Inclined to Censure'),
('hymns_church', 236, 'Lord, Accept into Thy Kingdom'),
('hymns_church', 237, 'Do What Is Right'),
('hymns_church', 238, 'Behold Thy Sons and Daughters, Lord'),
('hymns_church', 239, 'Choose the Right'),
('hymns_church', 240, 'Know This, That Every Soul Is Free'),
('hymns_church', 241, 'Count Your Blessings'),
('hymns_church', 242, 'Praise God, from Whom All Blessings Flow'),
('hymns_church', 243, 'Let Us All Press On'),
('hymns_church', 244, 'Come Along, Come Along'),
('hymns_church', 245, 'This House We Dedicate to Thee'),
('hymns_church', 246, 'Onward, Christian Soldiers'),
('hymns_church', 247, 'We Love Thy House, O God'),
('hymns_church', 248, 'Up, Awake, Ye Defenders of Zion'),
('hymns_church', 249, 'Called to Serve'),
('hymns_church', 250, 'We Are All Enlisted'),
('hymns_church', 251, 'Behold! A Royal Army'),
('hymns_church', 252, 'Put Your Shoulder to the Wheel'),
('hymns_church', 253, 'Like Ten Thousand Legions Marching'),
('hymns_church', 254, 'True to the Faith'),
('hymns_church', 255, 'Carry On'),
('hymns_church', 256, 'As Zion’s Youth in Latter Days'),
('hymns_church', 257, 'Rejoice! A Glorious Sound Is Heard'),
('hymns_church', 258, 'O Thou Rock of Our Salvation'),
('hymns_church', 259, 'Hope of Israel'),
('hymns_church', 260, 'Who’s on the Lord’s Side?'),
('hymns_church', 261, 'Thy Servants Are Prepared'),
('hymns_church', 262, 'Go, Ye Messengers of Glory'),
('hymns_church', 263, 'Go Forth with Faith'),
('hymns_church', 264, 'Hark, All Ye Nations!'),
('hymns_church', 265, 'Arise, O God, and Shine'),
('hymns_church', 266, 'The Time Is Far Spent'),
('hymns_church', 267, 'How Wondrous and Great'),
('hymns_church', 268, 'Come, All Whose Souls Are Lighted'),
('hymns_church', 269, 'Jehovah, Lord of Heaven and Earth'),
('hymns_church', 270, 'I’ll Go Where You Want Me to Go'),
('hymns_church', 271, 'Oh, Holy Words of Truth and Love'),
('hymns_church', 272, 'Oh Say, What Is Truth?'),
('hymns_church', 273, 'Truth Reflects upon Our Senses'),
('hymns_church', 274, 'The Iron Rod'),
('hymns_church', 275, 'Men Are That They Might Have Joy'),
('hymns_church', 276, 'Come Away to the Sunday School'),
('hymns_church', 277, 'As I Search the Holy Scriptures'),
('hymns_church', 278, 'Thanks for the Sabbath School'),
('hymns_church', 279, 'Thy Holy Word'),
('hymns_church', 280, 'Welcome, Welcome, Sabbath Morning'),
('hymns_church', 281, 'Help Me Teach with Inspiration'),
('hymns_church', 282, 'We Meet Again in Sabbath School'),
('hymns_church', 283, 'The Glorious Gospel Light Has Shone'),
('hymns_church', 284, 'If You Could Hie to Kolob'),
('hymns_church', 285, 'God Moves in a Mysterious Way'),
('hymns_church', 286, 'Oh, What Songs of the Heart'),
('hymns_church', 287, 'Rise, Ye Saints, and Temples Enter'),
('hymns_church', 288, 'How Beautiful Thy Temples, Lord'),
('hymns_church', 289, 'Holy Temples on Mount Zion'),
('hymns_church', 290, 'Rejoice, Ye Saints of Latter Days'),
('hymns_church', 291, 'Turn Your Hearts'),
('hymns_church', 292, 'O My Father'),
('hymns_church', 293, 'Each Life That Touches Ours for Good'),
('hymns_church', 294, 'Love at Home'),
('hymns_church', 295, 'O Love That Glorifies the Son'),
('hymns_church', 296, 'Our Father, by Whose Name'),
('hymns_church', 297, 'From Homes of Saints Glad Songs Arise'),
('hymns_church', 298, 'Home Can Be a Heaven on Earth'),
('hymns_church', 300, 'Families Can Be Together Forever'),
('hymns_church', 301, 'I Am a Child of God'),
('hymns_church', 302, 'I Know My Father Lives'),
('hymns_church', 303, 'Keep the Commandments'),
('hymns_church', 304, 'Teach Me to Walk in the Light'),
('hymns_church', 305, 'The Light Divine'),
('hymns_church', 306, 'God’s Daily Care'),
('hymns_church', 307, 'In Our Lovely Deseret'),
('hymns_church', 308, 'Love One Another'),
('hymns_church', 309, 'As Sisters in Zion'),
('hymns_church', 310, 'A Key Was Turned in Latter Days'),
('hymns_church', 311, 'We Meet Again as Sisters'),
('hymns_church', 312, 'We Ever Pray for Thee'),
('hymns_church', 313, 'God Is Love'),
('hymns_church', 314, 'How Gentle God’s Commands'),
('hymns_church', 315, 'Jesus, the Very Thought of Thee'),
('hymns_church', 316, 'The Lord Is My Shepherd'),
('hymns_church', 317, 'Sweet Is the Work'),
('hymns_church', 318, 'Love at Home'),
('hymns_church', 319, 'Ye Elders of Israel'),
('hymns_church', 320, 'The Priesthood of Our Lord'),
('hymns_church', 321, 'Ye Who Are Called to Labor'),
('hymns_church', 322, 'Come, All Ye Sons of God'),
('hymns_church', 323, 'Rise Up, O Men of God'),
('hymns_church', 324, 'Rise Up, O Men of God'),
('hymns_church', 325, 'See the Mighty Priesthood Gathered'),
('hymns_church', 326, 'Come, Come, Ye Saints'),
('hymns_church', 327, 'Go, Ye Messengers of Heaven'),
('hymns_church', 328, 'An Angel from on High'),
('hymns_church', 329, 'Thy Servants Are Prepared'),
('hymns_church', 330, 'See, the Mighty Angel Flying'),
('hymns_church', 331, 'Oh Say, What Is Truth?'),
('hymns_church', 332, 'Come, O Thou King of Kings'),
('hymns_church', 333, 'High on the Mountain Top'),
('hymns_church', 334, 'I Need Thee Every Hour'),
('hymns_church', 335, 'Brightly Beams Our Father’s Mercy'),
('hymns_church', 336, 'School Thy Feelings'),
('hymns_church', 337, 'O Home Beloved'),
('hymns_church', 338, 'America the Beautiful'),
('hymns_church', 339, 'My Country, ’Tis of Thee'),
('hymns_church', 340, 'The Star-Spangled Banner'),
('hymns_church', 341, 'God Save the King'),
('hymns_home_church', 1001, 'Come, Thou Fount of Every Blessing'),
('hymns_home_church', 1002, 'When the Savior Comes Again'),
('hymns_home_church', 1003, 'It Is Well with My Soul'),
('hymns_home_church', 1004, 'I Will Walk with Jesus'),
('hymns_home_church', 1005, 'His Eye Is on the Sparrow'),
('hymns_home_church', 1006, 'Think a Sacred Song'),
('hymns_home_church', 1007, 'As Bread Is Broken'),
('hymns_home_church', 1008, 'Bread of Life, Living Water'),
('hymns_home_church', 1009, 'Gethsemane'),
('hymns_home_church', 1010, 'Amazing Grace'),
('hymns_home_church', 1011, 'Holding Hands Around the World'),
('hymns_home_church', 1012, 'Anytime, Anywhere'),
('hymns_home_church', 1013, 'God’s Gracious Love'),
('hymns_home_church', 1014, 'My Shepherd Will Supply My Need'),
('hymns_home_church', 1015, 'Oh, the Deep, Deep Love of Jesus'),
('hymns_home_church', 1016, 'Behold the Wounds in Jesus’ Hands'),
('hymns_home_church', 1017, 'This Is the Christ'),
('hymns_home_church', 1018, 'Come, Lord Jesus'),
('hymns_home_church', 1019, 'To Love like Thee'),
('hymns_home_church', 1020, 'Softly and Tenderly Jesus Is Calling'),
('hymns_home_church', 1021, 'I Know That My Savior Loves Me'),
('hymns_home_church', 1022, 'Faith in Every Footstep'),
('hymns_home_church', 1023, 'Standing on the Promises'),
('hymns_home_church', 1024, 'I Have Faith in the Lord Jesus Christ'),
('hymns_home_church', 1025, 'Take My Heart and Let It Be Consecrated'),
('hymns_home_church', 1026, 'Holy Places'),
('hymns_home_church', 1027, 'Welcome Home'),
('hymns_home_church', 1028, 'This Little Light of Mine'),
('hymns_home_church', 1029, 'I Can’t Count Them All'),
('hymns_home_church', 1030, 'Close as a Quiet Prayer'),
('hymns_home_church', 1031, 'Come, Hear the Word the Lord Has Spoken'),
('hymns_home_church', 1032, 'Look unto Christ'),
('hymns_home_church', 1033, 'Oh, How Great Is Our Joy'),
('hymns_home_church', 1034, 'I’m a Pioneer Too'),
('hymns_home_church', 1035, 'As I Keep the Sabbath Day'),
('hymns_home_church', 1036, 'Read the Book of Mormon and Pray'),
('hymns_home_church', 1037, 'I’m Gonna Live So God Can Use Me'),
('hymns_home_church', 1038, 'The Lord’s My Shepherd'),
('hymns_home_church', 1039, 'Because'),
('hymns_home_church', 1040, 'His Voice as the Sound'),
('hymns_home_church', 1041, 'O Lord, Who Gave Thy Life for Me'),
('hymns_home_church', 1042, 'Thou Gracious God, Whose Mercy Lends'),
('hymns_home_church', 1043, 'Help Us Remember'),
('hymns_home_church', 1044, 'How Did the Savior Minister?'),
('hymns_home_church', 1045, 'Jesus Is the Way'),
('hymns_home_church', 1046, 'Can You Count the Stars in Heaven?'),
('hymns_home_church', 1047, 'He Cares for Me'),
('hymns_home_church', 1048, 'Our Prayer to Thee'),
('hymns_home_church', 1049, 'Joseph Prayed in Faith'),
('hymns_home_church', 1050, 'Stand by Me'),
('hymns_home_church', 1051, 'This Day Is a Good Day, Lord'),
('hymns_home_church', 1201, 'Hail the Day That Sees Him Rise'),
('hymns_home_church', 1202, 'He Is Born, the Divine Christ Child'),
('hymns_home_church', 1203, 'What Child Is This?'),
('hymns_home_church', 1204, 'Star Bright'),
('hymns_home_church', 1205, 'Let Easter Anthems Ring'),
('hymns_home_church', 1206, 'Were You There?'),
('hymns_home_church', 1207, 'Still, Still, Still'),
('hymns_home_church', 1208, 'Go Tell It on the Mountain'),
('hymns_home_church', 1209, 'Little Baby in a Manger')
ON CONFLICT (book_id, hymn_number) DO UPDATE SET title = EXCLUDED.title;
